valor1 = input("Digite um valor: ")
valor2 = input("Digite o segundo valor: ")
soma = float(valor1) + int(valor2)
print(F"A soma é {soma}")
subtracao =  float(valor1) - float(valor2)
print(f"A subtração entre os valores é: {subtracao}")
multiplicacao = float(valor1) * float(valor2)
print(f"A multiplicação entre os valores é: {multiplicacao}")
divisao = float(valor1) / float(valor2)
print(f"A divisão dos valores é: {divisao}")